spring.application.name=lostandfound

# URL contendo apenas a especificação do JDBC e o HOST (sem usuário e senha no meio)
spring.datasource.url=

# O usuário do Pooler vai isolado neste parâmetro
spring.datasource.username=postgres.gxvbkdfwuyqewmhqeztr

# A sua senha real do Supabase vai isolada neste parâmetro
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update